Add language filter
bukinoshita/open-source pull request #12
Opened 2017-02-25 09:23 UTC by jackyho112

2017-02-25 16:24 UTC, bukinoshita requested changes
Awesome work @jackyho112! It's looking really good 🎉 🌮  It's working like a charm! Loved!

I requested some changes on the pull request before merging, but also want to point some/others things here

## Some thought:

### env.js example
You may want to add an example for `env.js` on `README.md` and how to use it. Some people may have problems not knowing how to configure it. (or create an issue to add later)

### Missing space on footer
You've created `components/Footer.js` and now there's no space between `byBu` and `onGithub`. Should be `by Bu` and `on Github`.

### Filter
Button container CSS:
```css
.button__container {
  background-color: #ffffff;
  margin-bottom: 50px;
  padding-left: 15px;
  padding-top: 15px;
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
}
```

Change to:

```css
.button__container {
  background-color: #ffffff;
  margin-bottom: 50px;
  padding-left: 15px;
  padding-top: 15px;
  padding-right: 15px;
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
}
```

On `.filter__button` just remove `margin-right: 15px`.

And then add a `.filter__button--fake` to make the alignment right

Check on on `index.js` we have an example:
```html
<ul className="list">
  {issueList}

  <li className="fakeit"/>
  <li className="fakeit"/>
</ul>
```

### List Item

This should be inside the `<a class="list-item-link">` and also remove the class `row` on this div.
```js
<div className="row">
  {
    props.languages.map((language) => (
      <button onClick={() => props.onCategoryFilter(language)} key={`${language}-list-item`}>
        {language}
      </button>
    ))
  }
</div>
```

2017-02-25 16:24 UTC, bukinoshita commented on components/ListItem.js
> +    <div className="row">
Add this `div` inside the `<a className="list-item-link" href={props.html_url}>` and remove the class `row` of it

2017-02-25 16:24 UTC, bukinoshita commented on components/Footer.js
> +      Made by
Missing space between `by` and `Bu` (byBu)

2017-02-25 16:24 UTC, bukinoshita commented on components/Footer.js
> +      . Check this project on
Missing space between `on` and `Github` (onGithub)

2017-02-25 16:24 UTC, bukinoshita commented on pages/index.js
> +import flatten from 'lodash/flatten'
I think you can import `lodash` like this, give it a try:

```js
import { flatten, uniq, includes, set } from 'lodash'
```

2017-02-25 17:12 UTC, jackyho112 commented
@bukinoshita I was going to ask for your feedback but then you already did it 😃 . Thanks for your comments. I will make the changes and then ask for your thought again. Also, the language filters within the list item are just plain buttons for now. I can fix them to match the design once I get the SVGs 👍 .

2017-02-25 17:22 UTC, bukinoshita commented
Cool! All the functionality is working flawless as far as I tested 🥇 

I just realized that there's too many programming language LOL

So I quickly mockup this for you
![screenshot 2017-02-25 12 19 14](https://cloud.githubusercontent.com/assets/6929565/23333153/ba71389a-fb54-11e6-98eb-f00619cf081e.png)

```html
<span style="
  font-size: 12px;
  background-color: #5f357d;
  color: #fff;
  padding: 6px 8px;
  margin-bottom: 10px;
  display: inline-block;
">Javascript</span>
```

By doing that, you may want to increase `.list-item` height
```css
.list-item {
  background-color: #fff;
  flex-basis: 32%;
  margin-bottom: 25px;
  box-shadow: 0 2px 10px rgba(0, 0, 0, .2);
  transition: .15s;
  min-height: 220px; /* it was 200px */
  max-height: 220px;  /* it was 200px */
  overflow: hidden;
}

2017-02-25 18:19 UTC, jackyho112 commented
@bukinoshita Hello, I made some changes as requested. The only thing I didn't do is to align the filter buttons with fake buttons. I'm not sure how to achieve that with a variable number of filter buttons/languages using the fake button mechanic. I could do that with `margin-right: 10px` on the button and `justify-content: center` on the container. Not sure if that's how you want it to look though. Let me know your thought. I am open to anything 😄 .

Another note is that the performance could drop for having a large number of list items from a small number of list items. One example is changing from the C language filter to the zero language filter. One possible solution is to not use the `Truncate` component. Not sure about the alternative but that's just an idea. 

Let me know if there is anything else you want to give feedback on. I will love to hear your thoughts on anything. 🥂

2017-02-25 18:55 UTC, bukinoshita commented
I just realized something @jackyho112. We should get the repository language for `list-item` from [here](https://api.github.com/repos/bukinoshita/open-source) instead of having an array of languages

```
language: "JavaScript"
```

Some of them has too many languages, I guess would be better to show only Python as language since Python is the primary language of this repo (on this example below). What do you think?
![screenshot 2017-02-25 13 52 25](https://cloud.githubusercontent.com/assets/6929565/23333873/b02c5cb8-fb61-11e6-833a-cf9ea7a1236c.png)

I didn't understand this, can you explain to me what's happening?
> Another note is that the performance could drop for having a large number of list items from a small number of list items. One example is changing from the C language filter to the zero language filter. One possible solution is to not use the Truncate component. Not sure about the alternative but that's just an idea.

And again, thanks! You're doing an amazing work!

2017-02-26 00:08 UTC, jackyho112 commented
@bukinoshita I believe I am already getting the languages from this API endpoint(I think that's only way to get the information language for a repo). Currently, what I'm doing is get all the repo urls, get all the language urls from these repo urls and then map them to an object named `repoLanguageStore` in a variable. 

I'm not sure if showing only the one main language is the most user-friendly approach because someone may want to filter the issues with a language that may not be the main language of any repo. Once she gets the list, none of the issues shows that language as included, which may seem weird and unexpected. Maybe a 'More' button would be more appropriate. 

What I meant by my comment regarding performance is that loading a list of a large number of list items may take a bit longer than what the user deems responsive. One suggestion is to take off the `Truncate` component and maybe use something else or just implement what you need. But it's actually not a big deal.

Thank you again for the opportunity. I am glad I helped. Let me know if there is anything else you have in mind or any change you want.

2017-02-26 00:20 UTC, bukinoshita commented
Got it! I agree with you, let's stick with this then ☺️

I don't want to remove the truncate because we can't control the descriptions of the issues, some of them has large description.

Huge thanks!

2017-02-26 00:20 UTC, bukinoshita approved these changes

2017-02-26 00:20 UTC, merged

2017-03-20 09:23 UTC, ulgens commented
Did you release this feature? Current website has no filtering option or language information.

2017-03-20 12:10 UTC, bukinoshita commented
Yes @ulgens, this is the last version.

![kapture 2017-03-20 at 8 07 30](https://cloud.githubusercontent.com/assets/6929565/24099246/8e11c36c-0d44-11e7-8d23-49857393d72e.gif)